HOME_PRJ=/home/fengmaoqiao/workplace/vivado_ip_prj/rw_mac_phy_ip3/src 


vhdlcom -lib modema2_registers_rtl $HOME_PRJ/modema2_registers_rtl/modema2_registers_pkg.vhd
vhdlcom -lib endianness_converter_rtl $HOME_PRJ/endianness_converter_rtl/endianness_converter_pkg.vhd
vhdlcom -lib mapping_rtl $HOME_PRJ/mapping_rtl/functions_pkg.vhd
vhdlcom -lib fwt_rtl $HOME_PRJ/fwt_rtl/fwt_pkg.vhd
vhdlcom -lib modem_sm_b_rtl $HOME_PRJ/modem_sm_b_rtl/modem_sm_b_pkg.vhd
vhdlcom -lib bit_ser_adder_rtl $HOME_PRJ/bit_ser_adder_rtl/bit_ser_adder_pkg.vhd
vhdlcom -lib cordic_fft2_rtl $HOME_PRJ/cordic_fft2_rtl/cordic_fft2_pkg.vhd
vhdlcom -lib freq_corr_rtl $HOME_PRJ/freq_corr_rtl/freq_corr_pkg.vhd
vhdlcom -lib clockreset_maxim_rtl $HOME_PRJ/clockreset_maxim_rtl/clockreset_maxim_pkg.vhd
vhdlcom -lib freq_domain_rtl $HOME_PRJ/freq_domain_rtl/freq_domain_pkg.vhd
vhdlcom -lib barker_cor_rtl $HOME_PRJ/barker_cor_rtl/barker_cor_pkg.vhd
vhdlcom -lib rc4_crc_rtl $HOME_PRJ/rc4_crc_rtl/rc4_crc_pkg.vhd
vhdlcom -lib iq_compensation_rtl $HOME_PRJ/iq_compensation_rtl/iq_compensation_pkg.vhd
vhdlcom -lib postprocessing_rtl $HOME_PRJ/postprocessing_rtl/postprocessing_pkg.vhd
vhdlcom -lib init_sync_rtl $HOME_PRJ/init_sync_rtl/init_sync_pkg.vhd
vhdlcom -lib modem802_11a2_rtl $HOME_PRJ/modem802_11a2_rtl/modem802_11a2_pkg.vhd
vhdlcom -lib equalizer_rtl $HOME_PRJ/equalizer_rtl/equalizer_pkg.vhd
vhdlcom -lib cordic_vect_rtl $HOME_PRJ/cordic_vect_rtl/cordic_vect_pkg.vhd
vhdlcom -lib rx_equ_rtl $HOME_PRJ/rx_equ_rtl/rx_equ_pkg.vhd
vhdlcom -lib iq_estimation_rtl $HOME_PRJ/iq_estimation_rtl/iq_estimation_pkg.vhd
vhdlcom -lib tx_top_a2_rtl $HOME_PRJ/tx_top_a2_rtl/tx_top_a2_pkg.vhd
vhdlcom -lib ahb_config_pkg $HOME_PRJ/ahb_config_pkg/ahb_config_pkg.vhd
vhdlcom -lib aes_blockcipher_rtl $HOME_PRJ/aes_blockcipher_rtl/aes_blockcipher_pkg.vhd
vhdlcom -lib frontend_maxim_rtl $HOME_PRJ/frontend_maxim_rtl/frontend_maxim_pkg.vhd
vhdlcom -lib rx_top_rtl $HOME_PRJ/rx_top_rtl/rx_top_pkg.vhd
vhdlcom -lib phase_estimation_rtl $HOME_PRJ/phase_estimation_rtl/phase_estimation_pkg.vhd
vhdlcom -lib viterbi_rtl $HOME_PRJ/viterbi_rtl/viterbi_pkg.vhd
vhdlcom -lib radar_data_processing_rtl $HOME_PRJ/radar_data_processing_rtl/radar_data_processing_pkg.vhd
vhdlcom -lib rx11b_demod_rtl $HOME_PRJ/rx11b_demod_rtl/rx11b_demod_pkg.vhd
vhdlcom -lib stream_processor_rtl $HOME_PRJ/stream_processor_rtl/stream_processor_pkg.vhd
vhdlcom -lib radioctrl_maxair_rtl $HOME_PRJ/radioctrl_maxair_rtl/radioctrl_maxair_pkg.vhd
vhdlcom -lib radar_detection_rtl $HOME_PRJ/radar_detection_rtl/radar_detection_pkg.vhd
vhdlcom -lib rw_wlanbb_11g_maxim_rtl $HOME_PRJ/rw_wlanbb_11g_maxim_rtl/rw_wlanbb_11g_maxim_pkg.vhd
vhdlcom -lib sp_ahb_access_rtl $HOME_PRJ/sp_ahb_access_rtl/sp_ahb_access_pkg.vhd
vhdlcom -lib rx_ctrl_rtl $HOME_PRJ/rx_ctrl_rtl/rx_ctrl_pkg.vhd
vhdlcom -lib target_config_pkg $HOME_PRJ/target_config_pkg/target_config_pkg.vhd
vhdlcom -lib fft_shell_rtl $HOME_PRJ/fft_shell_rtl/fft_shell_pkg.vhd
vhdlcom -lib cordic_vectoring_rtl $HOME_PRJ/cordic_vectoring_rtl/cordic_vectoring_pkg.vhd
vhdlcom -lib wiener_filter_rtl $HOME_PRJ/wiener_filter_rtl/wiener_filter_pkg.vhd
vhdlcom -lib cordic_11h_rtl $HOME_PRJ/cordic_11h_rtl/cordic_11h_pkg.vhd
vhdlcom -lib residual_dc_offset_rtl $HOME_PRJ/residual_dc_offset_rtl/residual_dc_offset_pkg.vhd
vhdlcom -lib deintpun_rtl $HOME_PRJ/deintpun_rtl/deintpun_pkg.vhd
vhdlcom -lib modemg2bup_if_rtl $HOME_PRJ/modemg2bup_if_rtl/modemg2bup_if_pkg.vhd
vhdlcom -lib interleaver_rtl $HOME_PRJ/interleaver_rtl/interleaver_pkg.vhd
vhdlcom -lib link_quality_metric_rtl $HOME_PRJ/link_quality_metric_rtl/link_quality_metric_pkg.vhd
vhdlcom -lib biggest_picker_rtl $HOME_PRJ/biggest_picker_rtl/biggest_picker_pkg.vhd
vhdlcom -lib modem802_11g_rtl $HOME_PRJ/modem802_11g_rtl/modem802_11g_pkg.vhd
vhdlcom -lib time_domain_rtl $HOME_PRJ/time_domain_rtl/time_domain_pkg.vhd
vhdlcom -lib aes_ccm_rtl $HOME_PRJ/aes_ccm_rtl/aes_ccm_pkg.vhd
vhdlcom -lib modem802_11g_maxim_rtl $HOME_PRJ/modem802_11g_maxim_rtl/modem802_11g_maxim_pkg.vhd
vhdlcom -lib work $HOME_PRJ/slv_pkg.vhd
vhdlcom -lib pilot_tracking_rtl $HOME_PRJ/pilot_tracking_rtl/pilot_tracking_pkg.vhd
vhdlcom -lib preprocessing_rtl $HOME_PRJ/preprocessing_rtl/preprocessing_pkg.vhd
vhdlcom -lib commonlib $HOME_PRJ/commonlib/mdm_math_func_pkg.vhd
vhdlcom -lib iq_mismatch_rtl $HOME_PRJ/iq_mismatch_rtl/iq_mismatch_pkg.vhd
vhdlcom -lib radio_ctrl_maxair_rtl $HOME_PRJ/radioctrl_global_pkg.vhd
vhdlcom -lib work $HOME_PRJ/modem802_11b_pkg.vhd
vhdlcom -lib fine_freq_estim_rtl $HOME_PRJ/fine_freq_estim_rtl/fine_freq_estim_pkg.vhd
vhdlcom -lib modemb_registers_rtl $HOME_PRJ/modemb_registers_rtl/modemb_registers_pkg.vhd
vhdlcom -lib work $HOME_PRJ/modemg_registers_pkg.vhd
vhdlcom -lib cca_maxim_rtl $HOME_PRJ/cca_maxim_rtl/cca_maxim_pkg.vhd
vhdlcom -lib puncturer_rtl $HOME_PRJ/puncturer_rtl/puncturer_pkg.vhd
vhdlcom -lib agc_sp_rtl $HOME_PRJ/agc_sp_rtl/agc_sp_pkg.vhd
vhdlcom -lib channel_decoder_rtl $HOME_PRJ/channel_decoder_rtl/channel_decoder_pkg.vhd
vhdlcom -lib ramp_phase_rot_rtl $HOME_PRJ/ramp_phase_rot_rtl/ramp_phase_rot_pkg.vhd
vhdlcom -lib fft_2cordic_rtl $HOME_PRJ/fft_2cordic_rtl/fft_2cordic_pkg.vhd
vhdlcom -lib work $HOME_PRJ/eucl_divider_pkg.vhd
vhdlcom -lib agc_rtl $HOME_PRJ/agc_rtl/agc_pkg.vhd
vhdlcom -lib cordic_vectoring_11h_rtl $HOME_PRJ/cordic_vectoring_11h_rtl/cordic_vectoring_11h_pkg.vhd
vhdlcom -lib dsss_demod_rtl $HOME_PRJ/dsss_demod_rtl/dsss_demod_pkg.vhd
vhdlcom -lib cordic_rtl $HOME_PRJ/cordic_rtl/cordic_pkg.vhd
vhdlcom -lib tkip_key_mixing_rtl $HOME_PRJ/tkip_key_mixing_rtl/tkip_key_mixing_pkg.vhd
vhdlcom -lib rx_path_rtl $HOME_PRJ/rx_path_rtl/rx_path_pkg.vhd
vhdlcom -lib preamble_gen_rtl $HOME_PRJ/preamble_gen_rtl/preamble_gen_pkg.vhd
vhdlcom -lib tx_path_rtl $HOME_PRJ/tx_path_rtl/tx_path_pkg.vhd
vhdlcom -lib peak_detect_rtl $HOME_PRJ/peak_detect_rtl/peak_detect_pkg.vhd
vhdlcom -lib rx_predmx_rtl $HOME_PRJ/rx_predmx_rtl/rx_predmx_pkg.vhd
vhdlcom -lib sample_fifo_rtl $HOME_PRJ/sample_fifo_rtl/sample_fifo_pkg.vhd
vhdlcom -lib divider_rtl $HOME_PRJ/divider_rtl/divider_pkg.vhd
vhdlcom -lib decode_path_rtl $HOME_PRJ/decode_path_rtl/decode_path_pkg.vhd
vhdlcom -lib ahb_config_pkg $HOME_PRJ/ahb_config_pkg/ahb_config_pkg.vhd
vhdlcom -lib modem802_11a2_pkg $HOME_PRJ/modem802_11a2_pkg/modem802_11a2_pack.vhdvhdlcom -lib work $HOME_PRJ/rw_wlanbb_11g_maxim.vhd
vhdlcom -lib target_config_pkg $HOME_PRJ/target_config_pkg/target_config_pkg.vhd vhdlcom -lib work $HOME_PRJ/mapping.vhd

vhdlcom -lib work $HOME_PRJ/correlator.vhd
vhdlcom -lib work $HOME_PRJ/rc4_sboxgenerator.vhd
vhdlcom -lib work $HOME_PRJ/radar_registers_if.vhd
vhdlcom -lib work $HOME_PRJ/aes_invshiftrows.vhd
vhdlcom -lib work $HOME_PRJ/reset_controller.vhd
vhdlcom -lib work $HOME_PRJ/scan_muxes.vhd
vhdlcom -lib work $HOME_PRJ/wiener_filter.vhd
vhdlcom -lib work $HOME_PRJ/clockmodes_fsm.vhd
vhdlcom -lib work $HOME_PRJ/aes_control.vhd
vhdlcom -lib work $HOME_PRJ/bit_ser_adder.vhd
vhdlcom -lib work $HOME_PRJ/michael_blkfunc.vhd
vhdlcom -lib work $HOME_PRJ/preprocessing.vhd
vhdlcom -lib work $HOME_PRJ/cycle_counter.vhd
vhdlcom -lib work $HOME_PRJ/decode_path.vhd
vhdlcom -lib work $HOME_PRJ/punct_cpath.vhd
vhdlcom -lib work $HOME_PRJ/time_domain.vhd
vhdlcom -lib work $HOME_PRJ/srt_div.vhd
vhdlcom -lib work $HOME_PRJ/and_gate.vhd
vhdlcom -lib work $HOME_PRJ/iq_mismatch.vhd
vhdlcom -lib work $HOME_PRJ/channel_decoder.vhd
vhdlcom -lib work $HOME_PRJ/cordic_vectoring_11h.vhd
vhdlcom -lib work $HOME_PRJ/rx_equ_outstage1.vhd
vhdlcom -lib work $HOME_PRJ/iq_estimation.vhd
vhdlcom -lib work $HOME_PRJ/sp_registers.vhd
vhdlcom -lib work $HOME_PRJ/clockreset_core.vhd
vhdlcom -lib radioctrl_maxair_rtl $HOME_PRJ/radioctrl_maxair.vhd
vhdlcom -lib work $HOME_PRJ/interleaver.vhd
vhdlcom -lib work $HOME_PRJ/key_mixing_sbox.vhd
vhdlcom -lib work $HOME_PRJ/eucl_divider.vhd
vhdlcom -lib work $HOME_PRJ/puncturer.vhd
vhdlcom -lib work $HOME_PRJ/inv_matrix.vhd
vhdlcom -lib work $HOME_PRJ/master_interface.vhd
vhdlcom -lib work $HOME_PRJ/sigma_lut.vhd
vhdlcom -lib work $HOME_PRJ/b_clock_gate.vhd
vhdlcom -lib work $HOME_PRJ/err_phasor.vhd
vhdlcom -lib work $HOME_PRJ/en_20m_gen.vhd
vhdlcom -lib work $HOME_PRJ/radioctrl_registers.vhd
vhdlcom -lib work $HOME_PRJ/shift_fifo.vhd
vhdlcom -lib work $HOME_PRJ/alpha_shift.vhd
vhdlcom -lib work $HOME_PRJ/aes_encrypt.vhd
vhdlcom -lib work $HOME_PRJ/long_sfd_comp.vhd
vhdlcom -lib work $HOME_PRJ/tx_resync_80to60.vhd
vhdlcom -lib work $HOME_PRJ/adder4.vhd
vhdlcom -lib work $HOME_PRJ/modemb_registers_if.vhd
vhdlcom -lib work $HOME_PRJ/complex_mult_autocorr.vhd
vhdlcom -lib work $HOME_PRJ/comb_stage_vectoring.vhd
vhdlcom -lib work $HOME_PRJ/cordic_vectoring.vhd
vhdlcom -lib work $HOME_PRJ/rx_descr.vhd
vhdlcom -lib work $HOME_PRJ/max_decision.vhd
vhdlcom -lib work $HOME_PRJ/key_mixing_sm.vhd
vhdlcom -lib work $HOME_PRJ/signal_control.vhd
vhdlcom -lib work $HOME_PRJ/uart_divider.vhd
vhdlcom -lib work $HOME_PRJ/reset_gate2.vhd
vhdlcom -lib work $HOME_PRJ/keymix_phase2.vhd
vhdlcom -lib work $HOME_PRJ/microrotation.vhd
vhdlcom -lib work $HOME_PRJ/modem_rx_sm.vhd
vhdlcom -lib work $HOME_PRJ/delay_line18.vhd
vhdlcom -lib work $HOME_PRJ/iq_mism_ph_est.vhd
vhdlcom -lib work $HOME_PRJ/cca_maxim.vhd
vhdlcom -lib work $HOME_PRJ/rx_equ_instage0_ctr.vhd
vhdlcom -lib work $HOME_PRJ/cordic_vect.vhd
vhdlcom -lib work $HOME_PRJ/aes_subbytes.vhd
vhdlcom -lib work $HOME_PRJ/punct_dpath.vhd
vhdlcom -lib work $HOME_PRJ/arctan_lut.vhd
vhdlcom -lib work $HOME_PRJ/shift_adder_11h.vhd
vhdlcom -lib work $HOME_PRJ/endianness_converter.vhd
vhdlcom -lib work $HOME_PRJ/radar_detection.vhd
vhdlcom -lib work $HOME_PRJ/qerr_mult.vhd
vhdlcom -lib work $HOME_PRJ/divider.vhd
vhdlcom -lib work $HOME_PRJ/t1t2_preamble_mux.vhd
vhdlcom -lib work $HOME_PRJ/modema2_registers.vhd
vhdlcom -lib work $HOME_PRJ/phase_estimation.vhd
vhdlcom -lib work $HOME_PRJ/channel_decoder_data.vhd
vhdlcom -lib work $HOME_PRJ/tx_path_core.vhd
vhdlcom -lib work $HOME_PRJ/rx_equ_instage2.vhd
vhdlcom -lib work $HOME_PRJ/three_correlators.vhd
vhdlcom -lib work $HOME_PRJ/wiener_multadd2.vhd
vhdlcom -lib work $HOME_PRJ/shift_param_gen.vhd
vhdlcom -lib work $HOME_PRJ/bup2modem_sync.vhd
vhdlcom -lib work $HOME_PRJ/kalman.vhd
vhdlcom -lib work $HOME_PRJ/butterfly.vhd
vhdlcom -lib work $HOME_PRJ/est_mag.vhd
vhdlcom -lib work $HOME_PRJ/mapper.vhd
vhdlcom -lib work $HOME_PRJ/inverter_gate.vhd
vhdlcom -lib work $HOME_PRJ/iq_mism_g_est.vhd
vhdlcom -lib work $HOME_PRJ/cordic_combstage.vhd
vhdlcom -lib work $HOME_PRJ/cca_fsm_maxim.vhd
vhdlcom -lib work $HOME_PRJ/rc4_crc.vhd
vhdlcom -lib work $HOME_PRJ/modem802_11b_core.vhd
vhdlcom -lib work $HOME_PRJ/signal_datapath.vhd
vhdlcom -lib work $HOME_PRJ/shared_fifo_mem.vhd
vhdlcom -lib work $HOME_PRJ/tcombine_preamble_mux.vhd
vhdlcom -lib work $HOME_PRJ/phase_slope_comput.vhd
vhdlcom -lib work $HOME_PRJ/divider_cell.vhd
vhdlcom -lib work $HOME_PRJ/rssi_ctrl.vhd
vhdlcom -lib work $HOME_PRJ/biggest_picker.vhd
vhdlcom -lib work $HOME_PRJ/descrambling8_8.vhd
vhdlcom -lib work $HOME_PRJ/beta_shift.vhd
vhdlcom -lib work $HOME_PRJ/aes_invsubbytes.vhd
vhdlcom -lib work $HOME_PRJ/aes_mixcolumns.vhd
vhdlcom -lib work $HOME_PRJ/ramp_phase_rot.vhd
vhdlcom -lib work $HOME_PRJ/modem_tx_sm.vhd
vhdlcom -lib work $HOME_PRJ/t1t2_demux.vhd
vhdlcom -lib work $HOME_PRJ/cca_timers_maxim.vhd
vhdlcom -lib work $HOME_PRJ/crc32_8.vhd
vhdlcom -lib work $HOME_PRJ/keymix_phase1.vhd
vhdlcom -lib work $HOME_PRJ/serializer.vhd
vhdlcom -lib work $HOME_PRJ/modemg2bup_if.vhd
vhdlcom -lib work $HOME_PRJ/iq_compensation.vhd
vhdlcom -lib work $HOME_PRJ/residual_dc_offset.vhd
vhdlcom -lib work $HOME_PRJ/fft_shell.vhd
vhdlcom -lib work $HOME_PRJ/crc16_8.vhd
vhdlcom -lib work $HOME_PRJ/rx_equ_instage0.vhd
vhdlcom -lib work $HOME_PRJ/microrotation_11h.vhd
vhdlcom -lib work $HOME_PRJ/complex_mult.vhd
vhdlcom -lib work $HOME_PRJ/rc4_keyloading.vhd
vhdlcom -lib work $HOME_PRJ/clock_cleaner.vhd
vhdlcom -lib work $HOME_PRJ/deintpun_datapath.vhd
vhdlcom -lib work $HOME_PRJ/deintpun_control.vhd
vhdlcom -lib work $HOME_PRJ/mon_sto_cpe.vhd
vhdlcom -lib work $HOME_PRJ/rx_ctrl.vhd
vhdlcom -lib work $HOME_PRJ/ffwd_estimation.vhd
vhdlcom -lib work $HOME_PRJ/preamble_gen.vhd
vhdlcom -lib work $HOME_PRJ/aes_blockcipher.vhd
vhdlcom -lib work $HOME_PRJ/freq_corr.vhd
vhdlcom -lib work $HOME_PRJ/resync_cell.vhd
vhdlcom -lib work $HOME_PRJ/encoder.vhd
vhdlcom -lib work $HOME_PRJ/rx_equ.vhd
vhdlcom -lib work $HOME_PRJ/deintpun.vhd
vhdlcom -lib work $HOME_PRJ/radar_trigger.vhd
vhdlcom -lib work $HOME_PRJ/clk_dbg_cell.vhd
vhdlcom -lib work $HOME_PRJ/pilot_tracking.vhd
vhdlcom -lib work $HOME_PRJ/kalman_lut.vhd
vhdlcom -lib work $HOME_PRJ/modem2bup_sync.vhd
vhdlcom -lib work $HOME_PRJ/init_sync.vhd
vhdlcom -lib work $HOME_PRJ/biggest_picker_4.vhd
vhdlcom -lib work $HOME_PRJ/clock_divider.vhd
vhdlcom -lib work $HOME_PRJ/or_gate.vhd
vhdlcom -lib work $HOME_PRJ/barker_cor.vhd
vhdlcom -lib work $HOME_PRJ/comb_stage_vectoring_11h.vhd
vhdlcom -lib work $HOME_PRJ/ang_freq_conv.vhd
vhdlcom -lib work $HOME_PRJ/modem802_11g_core.vhd
vhdlcom -lib work $HOME_PRJ/rc4_sboxinit.vhd
vhdlcom -lib work $HOME_PRJ/interl_ctrl.vhd
vhdlcom -lib work $HOME_PRJ/modema_tx_sm.vhd
vhdlcom -lib work $HOME_PRJ/rc4_control.vhd
vhdlcom -lib work $HOME_PRJ/rx_top.vhd
vhdlcom -lib work $HOME_PRJ/cordic_fft2_stage.vhd
vhdlcom -lib work $HOME_PRJ/padding.vhd
vhdlcom -lib work $HOME_PRJ/clock_gating_unit.vhd
vhdlcom -lib work $HOME_PRJ/aes_decrypt.vhd
vhdlcom -lib work $HOME_PRJ/data_control.vhd
vhdlcom -lib work $HOME_PRJ/rx11b_demod.vhd
vhdlcom -lib work $HOME_PRJ/data_shift.vhd
vhdlcom -lib work $HOME_PRJ/equalizer.vhd
vhdlcom -lib work $HOME_PRJ/interl_mem.vhd
vhdlcom -lib work $HOME_PRJ/diff_decoder.vhd
vhdlcom -lib work $HOME_PRJ/cordic_fft2.vhd
vhdlcom -lib work $HOME_PRJ/link_quality_metric.vhd
vhdlcom -lib work $HOME_PRJ/fa.vhd
vhdlcom -lib work $HOME_PRJ/rx_equ_instage0_hpowman.vhd
vhdlcom -lib work $HOME_PRJ/modemg_registers.vhd
vhdlcom -lib work $HOME_PRJ/aes_shiftrows.vhd
vhdlcom -lib work $HOME_PRJ/viterbi.vhd
vhdlcom -lib work $HOME_PRJ/eucl_divider_top.vhd
vhdlcom -lib work $HOME_PRJ/radar_fom_freq_report.vhd
vhdlcom -lib work $HOME_PRJ/sync_main_clk.vhd
vhdlcom -lib work $HOME_PRJ/serialif.vhd
vhdlcom -lib work $HOME_PRJ/state2byte.vhd
vhdlcom -lib work $HOME_PRJ/delay_line36.vhd
vhdlcom -lib work $HOME_PRJ/modem802_11a2_core.vhd
vhdlcom -lib work $HOME_PRJ/gating_control.vhd
vhdlcom -lib work $HOME_PRJ/slv_pkg.vhd
vhdlcom -lib work $HOME_PRJ/rx_equ_instage1.vhd
vhdlcom -lib work $HOME_PRJ/scrambling8_8.vhd
vhdlcom -lib work $HOME_PRJ/fine_freq_estim.vhd
vhdlcom -lib work $HOME_PRJ/aes_invmixcolumns.vhd
vhdlcom -lib work $HOME_PRJ/watchdog_timer.vhd
vhdlcom -lib work $HOME_PRJ/unwrap_phase.vhd
vhdlcom -lib work $HOME_PRJ/radar_registers.vhd
vhdlcom -lib work $HOME_PRJ/pilot_scr.vhd
vhdlcom -lib work $HOME_PRJ/freq_domain.vhd
vhdlcom -lib work $HOME_PRJ/sp_ahb_access.vhd
vhdlcom -lib work $HOME_PRJ/complex_mult_corr.vhd
vhdlcom -lib work $HOME_PRJ/real_dot_product.vhd
vhdlcom -lib work $HOME_PRJ/complex_4mult.vhd
vhdlcom -lib work $HOME_PRJ/regbank_maxim.vhd
vhdlcom -lib radioctrl_maxair_rtl $HOME_PRJ/radioctrl_global_pkg.vhd
vhdlcom -lib work $HOME_PRJ/rx_equ_fsm.vhd
vhdlcom -lib work $HOME_PRJ/modem802_11b_pkg.vhd
vhdlcom -lib work $HOME_PRJ/hardware_filtering.vhd
vhdlcom -lib work $HOME_PRJ/max_picker_2.vhd
vhdlcom -lib work $HOME_PRJ/modem_sm_b.vhd
vhdlcom -lib work $HOME_PRJ/rx_predmx.vhd
vhdlcom -lib work $HOME_PRJ/radar_detection_ctrl.vhd
vhdlcom -lib work $HOME_PRJ/equalize_pilots.vhd
vhdlcom -lib work $HOME_PRJ/rx_mac_if.vhd
vhdlcom -lib work $HOME_PRJ/peak_detect.vhd
vhdlcom -lib work $HOME_PRJ/ext_sto_cpe.vhd
vhdlcom -lib work $HOME_PRJ/modem802_11g_maxim.vhd
vhdlcom -lib work $HOME_PRJ/modemg_registers_pkg.vhd
vhdlcom -lib work $HOME_PRJ/sample_fifo_sm.vhd
vhdlcom -lib work $HOME_PRJ/ff_estim_sm.vhd
vhdlcom -lib work $HOME_PRJ/phase_ramp.vhd
vhdlcom -lib work $HOME_PRJ/output_modes.vhd
vhdlcom -lib work $HOME_PRJ/wiener_ctrl.vhd
vhdlcom -lib work $HOME_PRJ/wiener_coeff.vhd
vhdlcom -lib work $HOME_PRJ/fwt.vhd
vhdlcom -lib work $HOME_PRJ/diag_gates.vhd
vhdlcom -lib work $HOME_PRJ/postprocessing.vhd
vhdlcom -lib work $HOME_PRJ/phase_distance.vhd
vhdlcom -lib work $HOME_PRJ/cordic.vhd
vhdlcom -lib work $HOME_PRJ/deserializer.vhd
vhdlcom -lib work $HOME_PRJ/ff_estim_compute.vhd
vhdlcom -lib work $HOME_PRJ/mux_gate.vhd
vhdlcom -lib work $HOME_PRJ/scrambler_a2.vhd
vhdlcom -lib work $HOME_PRJ/aes_keyschedule.vhd
vhdlcom -lib work $HOME_PRJ/rx_equ_instage0_corman.vhd
vhdlcom -lib work $HOME_PRJ/cck_form.vhd
vhdlcom -lib work $HOME_PRJ/figure_of_merit.vhd
vhdlcom -lib work $HOME_PRJ/enable_1mhz_divider.vhd
vhdlcom -lib work $HOME_PRJ/tx_activ_gen.vhd
vhdlcom -lib work $HOME_PRJ/ha.vhd
vhdlcom -lib work $HOME_PRJ/demapping.vhd
vhdlcom -lib work $HOME_PRJ/sample_fifo.vhd
vhdlcom -lib work $HOME_PRJ/aes_sm.vhd
vhdlcom -lib work $HOME_PRJ/txrxcntrl.vhd
vhdlcom -lib work $HOME_PRJ/tkip_key_mixing.vhd
vhdlcom -lib work $HOME_PRJ/clock_gate.vhd
vhdlcom -lib work $HOME_PRJ/ffwd_filter.vhd
vhdlcom -lib work $HOME_PRJ/phase_computation.vhd
vhdlcom -lib work $HOME_PRJ/eucl_divider_pkg.vhd
vhdlcom -lib work $HOME_PRJ/filter.vhd
vhdlcom -lib work $HOME_PRJ/evm_calculator.vhd
vhdlcom -lib work $HOME_PRJ/rx_path_core.vhd
vhdlcom -lib work $HOME_PRJ/short_sfd_comp.vhd
vhdlcom -lib work $HOME_PRJ/viterbi_boundary.vhd
vhdlcom -lib work $HOME_PRJ/tx_top_a2.vhd
vhdlcom -lib work $HOME_PRJ/ring_buffer.vhd
vhdlcom -lib work $HOME_PRJ/peak_search.vhd
vhdlcom -lib work $HOME_PRJ/radar_data_processing.vhd
vhdlcom -lib work $HOME_PRJ/rx_equ_outstage2.vhd
vhdlcom -lib work $HOME_PRJ/fft_serial.vhd
vhdlcom -lib work $HOME_PRJ/mdma2_rx_sm.vhd
vhdlcom -lib work $HOME_PRJ/rx_resync_60to80.vhd
vhdlcom -lib work $HOME_PRJ/reset_gate.vhd
vhdlcom -lib work $HOME_PRJ/carrier_detect.vhd
vhdlcom -lib work $HOME_PRJ/reset_resync.vhd
vhdlcom -lib work $HOME_PRJ/clock_mux.vhd
vhdlcom -lib work $HOME_PRJ/shift_adder.vhd
vhdlcom -lib work $HOME_PRJ/cordic_11h.vhd
vhdlcom -lib work $HOME_PRJ/sync_hiss_sclk1.vhd
vhdlcom -lib work $HOME_PRJ/aes_ccm.vhd
vhdlcom -lib work $HOME_PRJ/channel_decoder_signal.vhd
vhdlcom -lib work $HOME_PRJ/error_gen.vhd
vhdlcom -lib work $HOME_PRJ/stream_processor.vhd
vhdlcom -lib work $HOME_PRJ/comp_angle.vhd
vhdlcom -lib work $HOME_PRJ/rx_equ_outstage0.vhd
vhdlcom -lib work $HOME_PRJ/str_proc_control.vhd
vhdlcom -lib work $HOME_PRJ/tx_mux.vhd
vhdlcom -lib work $HOME_PRJ/data_datapath.vhd
vhdlcom -lib work $HOME_PRJ/cca_gen_maxim.vhd
vhdlcom -lib work $HOME_PRJ/dsss_demod.vhd
vhdlcom -lib work $HOME_PRJ/clockreset_maxim.vhd
vhdlcom -lib work $HOME_PRJ/magnitude_gen.vhd
vhdlcom -lib work $HOME_PRJ/cck_mod.vhd
vhdlcom -lib work $HOME_PRJ/rc4_keystream.vhd
vhdlcom -lib work $HOME_PRJ/wie_mem.vhd
vhdlcom -lib work $HOME_PRJ/exp_lut.vhd
vhdlcom -lib work $HOME_PRJ/modemb_registers.vhd
vhdlcom -lib work $HOME_PRJ/cordic_combstage_11h.vhd
vhdlcom -lib work $HOME_PRJ/coarse_freq_sync.vhd
vhdlcom -lib work $HOME_PRJ/fft_2cordic.vhd
vhdlcom -lib work $HOME_PRJ/mac_interface.vhd
vhdlcom -lib work $HOME_PRJ/spreading.vhd
vhdlcom -lib work $HOME_PRJ/cca_resync_maxim.vhd
vhdlcom -lib work $HOME_PRJ/clock_sel_cntl.vhd
vhdlcom -lib work $HOME_PRJ/channel_decoder_control.vhd





vericom -lib work $HOME_PRJ/commonDefines.v
vericom -lib work $HOME_PRJ/commonDefine.v
vericom -lib work $HOME_PRJ/defineDMA.v
vericom -lib work $HOME_PRJ/defineAHB.v
vericom -lib work $HOME_PRJ/define.v


vericom -lib work $HOME_PRJ/RxStateCtl.v
vericom -lib work $HOME_PRJ/ccmpMux.v
vericom -lib work $HOME_PRJ/ahb_mpa.v
vericom -lib work $HOME_PRJ/txFifo.v
vericom -lib work $HOME_PRJ/formatMPDU.v
vericom -lib work $HOME_PRJ/scoreboardController.v
vericom -lib work $HOME_PRJ/xilinx_dual_port_memory_128x22_rf_wr/blk_mem_gen_v8_3_3/simulation/blk_mem_gen_v8_3.v
vericom -lib work $HOME_PRJ/xilinx_dual_port_memory_128x22_rf_wr/sim/xilinx_dual_port_memory_128x22_rf_wr.v
vericom -lib work $HOME_PRJ/global_define.v
vericom -lib work $HOME_PRJ/tsfSync.v
vericom -lib work $HOME_PRJ/fcs.v
vericom -lib work $HOME_PRJ/int_cntl.v
vericom -lib work $HOME_PRJ/intCtrlResync.v
vericom -lib work $HOME_PRJ/icv.v
vericom -lib work $HOME_PRJ/rxFifoController.v
vericom -lib work $HOME_PRJ/mibResync.v
vericom -lib work $HOME_PRJ/keySearchEngine.v
vericom -lib work $HOME_PRJ/tkip.v
vericom -lib work $HOME_PRJ/fifo_of_tx_and_rx/fifo_of_tx_and_rx_sim_netlist.v
vericom -lib work $HOME_PRJ/fifo_of_tx_and_rx/sim/fifo_of_tx_and_rx.v
vericom -lib work $HOME_PRJ/fifo_of_tx_and_rx/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v
vericom -lib work $HOME_PRJ/fifo_of_tx_and_rx/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v
vericom -lib work $HOME_PRJ/fifo_of_tx_and_rx/fifo_of_tx_and_rx_stub.v
vericom -lib work $HOME_PRJ/rw_nx_platform.v
vericom -lib work $HOME_PRJ/formatACK.v
vericom -lib work $HOME_PRJ/backoffProtTrig.v
vericom -lib work $HOME_PRJ/rxController.v
vericom -lib work $HOME_PRJ/macControllerTx.v
vericom -lib work $HOME_PRJ/aesCore.v
vericom -lib work $HOME_PRJ/simpleSynchro.v
vericom -lib work $HOME_PRJ/baController.v
vericom -lib work $HOME_PRJ/downstream_data_n_ack.v
vericom -lib work $HOME_PRJ/tx_mod.v
vericom -lib work $HOME_PRJ/rx_package_fifo/sim/rx_package_fifo.v
vericom -lib work $HOME_PRJ/rx_package_fifo/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v
vericom -lib work $HOME_PRJ/rx_package_fifo/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v
vericom -lib work $HOME_PRJ/deaggregator.v
vericom -lib work $HOME_PRJ/accessArbiter.v
vericom -lib work $HOME_PRJ/rxPrimCtrl.v
vericom -lib work $HOME_PRJ/wepTkip.v
vericom -lib work $HOME_PRJ/macControllerMaster.v
vericom -lib work $HOME_PRJ/intCtrlRegisters.v
vericom -lib work $HOME_PRJ/crcGenChk.v
vericom -lib work $HOME_PRJ/txFifoController.v
vericom -lib work $HOME_PRJ/intCtrlReg.v
vericom -lib work $HOME_PRJ/rx_mod.v
vericom -lib work $HOME_PRJ/macCorePIResync.v
vericom -lib work $HOME_PRJ/fifoPtrGray.v
vericom -lib work $HOME_PRJ/syncLevel.v
vericom -lib work $HOME_PRJ/formatBA.v
vericom -lib work $HOME_PRJ/memoryController.v
vericom -lib work $HOME_PRJ/aesKeyGenTop.v
vericom -lib work $HOME_PRJ/rxFIFOIfController.v
vericom -lib work $HOME_PRJ/upstream_busif.v
vericom -lib work $HOME_PRJ/divider.v
vericom -lib work $HOME_PRJ/baControllerFsm.v
vericom -lib work $HOME_PRJ/tx_mac_data_fifo_1/tx_mac_data_fifo_stub.v
vericom -lib work $HOME_PRJ/tx_mac_data_fifo_1/tx_mac_data_fifo_sim_netlist.v
vericom -lib work $HOME_PRJ/tx_mac_data_fifo_1/sim/tx_mac_data_fifo.v
vericom -lib work $HOME_PRJ/tx_mac_data_fifo_1/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v
vericom -lib work $HOME_PRJ/tx_mac_data_fifo_1/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v
vericom -lib work $HOME_PRJ/txParametersCache.v
vericom -lib work $HOME_PRJ/backoffCtrl.v
vericom -lib work $HOME_PRJ/rx_package_fifo_1/rx_package_fifo_sim_netlist.v
vericom -lib work $HOME_PRJ/rx_package_fifo_1/rx_package_fifo_stub.v
vericom -lib work $HOME_PRJ/rx_package_fifo_1/sim/rx_package_fifo.v
vericom -lib work $HOME_PRJ/rx_package_fifo_1/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v
vericom -lib work $HOME_PRJ/rx_package_fifo_1/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v
vericom -lib work $HOME_PRJ/ccmpTop.v
vericom -lib work $HOME_PRJ/aesControl.v
vericom -lib work $HOME_PRJ/nav.v
vericom -lib work $HOME_PRJ/clk_wiz_0/clk_wiz_0_stub.v
vericom -lib work $HOME_PRJ/clk_wiz_0/clk_wiz_0.v
vericom -lib work $HOME_PRJ/clk_wiz_0/clk_wiz_0_clk_wiz.v
vericom -lib work $HOME_PRJ/clk_wiz_0/clk_wiz_0_sim_netlist.v
vericom -lib work $HOME_PRJ/txPrimCtrlSelLogic.v
vericom -lib work $HOME_PRJ/txListProc.v
vericom -lib work $HOME_PRJ/dmaEngine.v
vericom -lib work $HOME_PRJ/Ahb2Apb.v
vericom -lib work $HOME_PRJ/downstream_busif.v
vericom -lib work $HOME_PRJ/dmaEngineWrapper.v
vericom -lib work $HOME_PRJ/formatCTS.v
vericom -lib work $HOME_PRJ/formatAMPDUDelimiter.v
vericom -lib work $HOME_PRJ/mac_data_fifo/mac_data_fifo_sim_netlist.v
vericom -lib work $HOME_PRJ/mac_data_fifo/sim/mac_data_fifo.v
vericom -lib work $HOME_PRJ/mac_data_fifo/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v
vericom -lib work $HOME_PRJ/mac_data_fifo/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v
vericom -lib work $HOME_PRJ/mac_data_fifo/mac_data_fifo_stub.v
vericom -lib work $HOME_PRJ/rdWrCtlr.v
vericom -lib work $HOME_PRJ/sram_mpa.v
vericom -lib work $HOME_PRJ/encryptRxCntrl.v
vericom -lib work $HOME_PRJ/txPrimCtrl.v
vericom -lib work $HOME_PRJ/macCSReg.v
vericom -lib work $HOME_PRJ/mibController.v
vericom -lib work $HOME_PRJ/encryptEngClkCntl.v
vericom -lib work $HOME_PRJ/ahbSlaveIF.v
vericom -lib work $HOME_PRJ/clock_ctrl.v
vericom -lib work $HOME_PRJ/rwWlanNxMACHW.v
vericom -lib work $HOME_PRJ/frameDecoder.v
vericom -lib work $HOME_PRJ/debugPortCtrl.v
vericom -lib work $HOME_PRJ/phy_top.v
vericom -lib work $HOME_PRJ/pulse2PulseSynchro.v
vericom -lib work $HOME_PRJ/intCtrl.v
vericom -lib work $HOME_PRJ/fifo_generator_0/sim/fifo_generator_0.v
vericom -lib work $HOME_PRJ/fifo_generator_0/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v
vericom -lib work $HOME_PRJ/fifo_generator_0/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v
vericom -lib work $HOME_PRJ/hostIfAhb.v
vericom -lib work $HOME_PRJ/rxListProc.v
vericom -lib work $HOME_PRJ/backoffPRNG.v
vericom -lib work $HOME_PRJ/regbank_if.v
vericom -lib work $HOME_PRJ/formatCFEND.v
vericom -lib work $HOME_PRJ/compare_fifo/sim/compare_fifo.v
vericom -lib work $HOME_PRJ/compare_fifo/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v
vericom -lib work $HOME_PRJ/compare_fifo/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v
vericom -lib work $HOME_PRJ/risingEdgeDetector.v
vericom -lib work $HOME_PRJ/commonDefineR2.v
vericom -lib work $HOME_PRJ/ccmCntl.v
vericom -lib work $HOME_PRJ/aligner.v
vericom -lib work $HOME_PRJ/rx_mac_data_fifo/sim/rx_mac_data_fifo.v
vericom -lib work $HOME_PRJ/rx_mac_data_fifo/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v
vericom -lib work $HOME_PRJ/rx_mac_data_fifo/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v
vericom -lib work $HOME_PRJ/ccmp.v
vericom -lib work $HOME_PRJ/downstream_req.v
vericom -lib work $HOME_PRJ/rxFifo.v
vericom -lib work $HOME_PRJ/tx_rx_fifo.v
vericom -lib work $HOME_PRJ/asyncXor.v
vericom -lib work $HOME_PRJ/fifo_of_tx_and_rx_1/sim/fifo_of_tx_and_rx.v
vericom -lib work $HOME_PRJ/fifo_of_tx_and_rx_1/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v
vericom -lib work $HOME_PRJ/fifo_of_tx_and_rx_1/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v
vericom -lib work $HOME_PRJ/backoffACSel.v
vericom -lib work $HOME_PRJ/aesSBox.v
vericom -lib work $HOME_PRJ/backoff.v
vericom -lib work $HOME_PRJ/mpiftxRxFifoControl.v
vericom -lib work $HOME_PRJ/dozeController.v
vericom -lib work $HOME_PRJ/dma_interface.v
vericom -lib work $HOME_PRJ/rxControllerFsm.v
vericom -lib work $HOME_PRJ/rx_mac_data_fifo_1/rx_mac_data_fifo_stub.v
vericom -lib work $HOME_PRJ/rx_mac_data_fifo_1/rx_mac_data_fifo_sim_netlist.v
vericom -lib work $HOME_PRJ/rx_mac_data_fifo_1/sim/rx_mac_data_fifo.v
vericom -lib work $HOME_PRJ/rx_mac_data_fifo_1/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v
vericom -lib work $HOME_PRJ/rx_mac_data_fifo_1/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v
vericom -lib work $HOME_PRJ/macCoreReg.v
vericom -lib work $HOME_PRJ/commonDefineR2Capt.v
vericom -lib work $HOME_PRJ/txBufferWepTkip.v
vericom -lib work $HOME_PRJ/system_ctrl.v
vericom -lib work $HOME_PRJ/TxStateCtl.v
vericom -lib work $HOME_PRJ/ccmpInReg.v
vericom -lib work $HOME_PRJ/commonDefineR3.v
vericom -lib work $HOME_PRJ/txController.v
vericom -lib work $HOME_PRJ/macControllerRx.v
vericom -lib work $HOME_PRJ/postWrite.v
vericom -lib work $HOME_PRJ/sBoxTKIP.v
vericom -lib work $HOME_PRJ/tx_mac_data_fifo/sim/tx_mac_data_fifo.v
vericom -lib work $HOME_PRJ/tx_mac_data_fifo/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v
vericom -lib work $HOME_PRJ/tx_mac_data_fifo/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v
vericom -lib work $HOME_PRJ/memory_models.v
vericom -lib work $HOME_PRJ/macController.v
vericom -lib work $HOME_PRJ/ccmpOutReg.v
vericom -lib work $HOME_PRJ/macphy_if.v
vericom -lib work $HOME_PRJ/ahbMasterIF.v
vericom -lib work $HOME_PRJ/macCore.v
vericom -lib work $HOME_PRJ/txVectorSel.v
vericom -lib work $HOME_PRJ/prng.v
vericom -lib work $HOME_PRJ/aesKeyInst.v
vericom -lib work $HOME_PRJ/rateSelection.v
vericom -lib work $HOME_PRJ/compare_fifo_1/compare_fifo_sim_netlist.v
vericom -lib work $HOME_PRJ/compare_fifo_1/compare_fifo_stub.v
vericom -lib work $HOME_PRJ/compare_fifo_1/sim/compare_fifo.v
vericom -lib work $HOME_PRJ/compare_fifo_1/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v
vericom -lib work $HOME_PRJ/compare_fifo_1/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v
vericom -lib work $HOME_PRJ/encryptRxBufCntrl.v
vericom -lib work $HOME_PRJ/ipc.v
vericom -lib work $HOME_PRJ/commonDefineR1.v
vericom -lib work $HOME_PRJ/upstream_req_n_data.v
vericom -lib work $HOME_PRJ/macPhyIf.v
vericom -lib work $HOME_PRJ/fallingEdgeDetector.v
vericom -lib work $HOME_PRJ/txTimeCalculatorAC.v
vericom -lib work $HOME_PRJ/txStatusUpdater.v
vericom -lib work $HOME_PRJ/rw_dini_dma.v
vericom -lib work $HOME_PRJ/macPlReg.v
vericom -lib work $HOME_PRJ/bus2ram.v
vericom -lib work $HOME_PRJ/commonDefineR1Capt.v
vericom -lib work $HOME_PRJ/toggleSynch1.v
vericom -lib work $HOME_PRJ/backoffCnt.v
vericom -lib work $HOME_PRJ/txControllerMainFSM.v
vericom -lib work $HOME_PRJ/decryptFsm.v
vericom -lib work $HOME_PRJ/dataLatch.v
vericom -lib work $HOME_PRJ/dma_ctrl.v
vericom -lib work $HOME_PRJ/upstream_ahbif.v
vericom -lib work $HOME_PRJ/upstream_ack.v
vericom -lib work $HOME_PRJ/ccm.v
vericom -lib work $HOME_PRJ/aesMixColumn.v
vericom -lib work $HOME_PRJ/commonDefineR3Capt.v
vericom -lib work $HOME_PRJ/syncBus.v
vericom -lib work $HOME_PRJ/dmaArbiter.v
vericom -lib work $HOME_PRJ/formatRTS.v
vericom -lib work $HOME_PRJ/encryptEngTop.v
vericom -lib work $HOME_PRJ/rw_nx_simulate_WL.v
vericom -lib work $HOME_PRJ/macTimerUnit.v


#verdi -lib work -top rw_wlanbb_11g_maxim
verdi -lib work -top rw_nx_platform

